package coop.campaign;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;

import static coop.util.CoopText.requireText;

/**
 * Everything that makes one market ship listing <em>that</em> ship rather than a pristine copy of its
 * base variant (Phase 12c gaps 2a + 2b; extended for Phase 32 shared storage).
 *
 * <p>Capturing {@code getHullVariantId()} alone loses two independent things. D-mods are not part of
 * the variant id: {@code DModManager.addDMods} writes them as <em>perma-mods</em> on a REFIT-source
 * variant ({@code removeSuppressedMod} + {@code addPermaMod}), and {@code DModManager.setDHull}
 * additionally swaps the hull spec to the {@code _dhull} variety. And combat readiness lives on the
 * fleet member's repair tracker, not the variant at all. A guest that rebuilt a listing from the
 * variant id got a clean hull at full CR, priced by its own engine accordingly — a visible,
 * exploitable divergence.
 *
 * <p><b>Why the Phase 32 fields exist.</b> A shop listing only has to <em>price</em> correctly; a
 * shared storage locker has to hand the ship back exactly as it went in. Weapon groups, the current
 * hull fraction, a player-typed variant display name and the module variants of a modular hull are
 * all things vanilla keeps on a mothballed member and none of them are recoverable from the fields
 * above, so a stored-and-withdrawn ship came back with autogenerated groups, full hull, its name
 * reset and pristine modules. Officers are deliberately <em>not</em> carried: vanilla keeps the
 * officer with the player when a ship is stored, so there is nothing on the member to send.
 *
 * <h2>Wire format (three nesting levels, plus module recursion)</h2>
 *
 * <p>The record is one {@code |}-separated {@link CoopDelimited} line, carried inside a single field
 * of the enclosing {@link CoopMarketSync} stock line (level 1) or of a {@code MARKET_TXN} payload.
 * {@code CoopDelimited.field}/{@code split} round-trip exactly one nesting level, so:
 *
 * <ul>
 *   <li><b>level 1</b> — the stock line, fields joined by {@code |};</li>
 *   <li><b>level 2</b> — this record, fields joined by {@code |}, the whole thing escaped once by the
 *       level-1 {@code field()} call;</li>
 *   <li><b>level 3</b> — the inner lists/maps, which {@code |} can no longer separate. Elements are
 *       joined by {@code ,} and map entries written {@code key=value}, with a local escape of
 *       {@code \} &rarr; {@code \\}, {@code ,} &rarr; {@code \c} and {@code =} &rarr; {@code \e}.
 *       That escape nests cleanly under the two {@code CoopDelimited} passes above because each pass
 *       escapes backslashes it finds and unescapes them symmetrically.</li>
 * </ul>
 *
 * <p><b>Unbounded nesting is safe, and that is what modules and weapon groups ride on.</b> Both
 * escapes are <em>total on the backslash</em>: {@code CoopDelimited.field} rewrites every {@code \}
 * it sees and {@link #cell} does the same, so no lone backslash survives either pass and every pass
 * is exactly inverted by its counterpart. A whole encoded {@code CoopShipDetail} can therefore be
 * stuffed into one level-3 cell of another one and come back byte-identical, at any depth. A weapon
 * group is encoded the same way — its own little {@code |} line inside a level-3 cell. Decoding
 * refuses to recurse past {@link #MAX_MODULE_NESTING} rather than let a malformed blob walk the
 * stack down.
 */
public record CoopShipDetail(String memberId,
                             String shipName,
                             String baseVariantId,
                             String hullSpecId,
                             float baseCR,
                             int vents,
                             int caps,
                             List<String> permaMods,
                             List<String> sMods,
                             List<String> sModdedBuiltIns,
                             List<String> refitMods,
                             List<String> suppressedMods,
                             Map<String, String> weapons,
                             Map<String, String> wings,
                             List<WeaponGroup> weaponGroups,
                             float hullFraction,
                             String displayName,
                             Map<String, CoopShipDetail> modules) {

    /** Number of {@code |}-separated fields in the encoded form. */
    public static final int FIELD_COUNT = 18;

    /**
     * How deep {@link #decode(String)} will follow module references. Vanilla's deepest modular hull
     * is one level (a station and its weapon platforms); anything past this is a malformed or hostile
     * blob, and recursing on it would be a stack overflow inside the snapshot apply.
     */
    public static final int MAX_MODULE_NESTING = 4;

    public CoopShipDetail {
        // Not requireText: a module carries no fleet-member id of its own (it is not a member), so
        // the empty string is a legal value here. The callers that need a real id — capture, which
        // drops a member without one, and the listing rebuild, which cannot delta-remove a listing it
        // cannot name — check for it and say so loudly there.
        memberId = CoopDelimited.normalize(memberId).trim();
        shipName = CoopDelimited.normalize(shipName);
        baseVariantId = requireText(baseVariantId, "baseVariantId");
        hullSpecId = CoopDelimited.normalize(hullSpecId);
        permaMods = copyList(permaMods);
        sMods = copyList(sMods);
        sModdedBuiltIns = copyList(sModdedBuiltIns);
        refitMods = copyList(refitMods);
        suppressedMods = copyList(suppressedMods);
        weapons = copyMap(weapons);
        wings = copyMap(wings);
        weaponGroups = copyGroups(weaponGroups);
        hullFraction = clampFraction(hullFraction);
        displayName = CoopDelimited.normalize(displayName);
        modules = copyModules(modules);
    }

    /**
     * The pre-Phase-32 shape: no weapon groups (the receiver autogenerates them), undamaged hull, no
     * display-name override and no modules. Kept because most listings genuinely are that, and
     * because it is what a module capture starts from.
     */
    public CoopShipDetail(String memberId,
                          String shipName,
                          String baseVariantId,
                          String hullSpecId,
                          float baseCR,
                          int vents,
                          int caps,
                          List<String> permaMods,
                          List<String> sMods,
                          List<String> sModdedBuiltIns,
                          List<String> refitMods,
                          List<String> suppressedMods,
                          Map<String, String> weapons,
                          Map<String, String> wings) {
        this(memberId, shipName, baseVariantId, hullSpecId, baseCR, vents, caps, permaMods, sMods,
                sModdedBuiltIns, refitMods, suppressedMods, weapons, wings,
                List.of(), 1f, "", Map.of());
    }

    public String encode() {
        return CoopDelimited.field(memberId)
                + '|' + CoopDelimited.field(shipName)
                + '|' + CoopDelimited.field(baseVariantId)
                + '|' + CoopDelimited.field(hullSpecId)
                + '|' + floatText(baseCR)
                + '|' + vents
                + '|' + caps
                + '|' + CoopDelimited.field(joinList(permaMods))
                + '|' + CoopDelimited.field(joinList(sMods))
                + '|' + CoopDelimited.field(joinList(sModdedBuiltIns))
                + '|' + CoopDelimited.field(joinList(refitMods))
                + '|' + CoopDelimited.field(joinList(suppressedMods))
                + '|' + CoopDelimited.field(joinMap(weapons))
                + '|' + CoopDelimited.field(joinMap(wings))
                + '|' + CoopDelimited.field(joinGroups(weaponGroups))
                + '|' + floatText(hullFraction)
                + '|' + CoopDelimited.field(displayName)
                + '|' + CoopDelimited.field(joinModules(modules));
    }

    public static CoopShipDetail decode(String encoded) {
        return decode(encoded, 0);
    }

    private static CoopShipDetail decode(String encoded, int depth) {
        Objects.requireNonNull(encoded, "encoded");
        if (depth > MAX_MODULE_NESTING) {
            throw new IllegalArgumentException("Ship detail nests deeper than " + MAX_MODULE_NESTING
                    + " module levels");
        }
        List<String> f = CoopDelimited.split(encoded);
        if (f.size() != FIELD_COUNT) {
            throw new IllegalArgumentException("Expected " + FIELD_COUNT + " ship detail fields, got " + f.size());
        }
        return new CoopShipDetail(f.get(0), f.get(1), f.get(2), f.get(3),
                Float.parseFloat(f.get(4).trim()),
                Integer.parseInt(f.get(5).trim()),
                Integer.parseInt(f.get(6).trim()),
                splitList(f.get(7)), splitList(f.get(8)), splitList(f.get(9)),
                splitList(f.get(10)), splitList(f.get(11)),
                splitMap(f.get(12)), splitMap(f.get(13)),
                splitGroups(f.get(14)),
                parseFraction(f.get(15)),
                f.get(16),
                splitModules(f.get(17), depth));
    }

    /**
     * One entry of the variant's {@code getWeaponGroups()} list: which slots fire together, whether
     * the group is LINKED or ALTERNATING, and whether autofire starts on.
     *
     * <p>The type is a boolean rather than the engine's {@code WeaponGroupType} so this record stays
     * free of game API imports (it is decoded on both sides of the wire and unit-tested without a
     * game installed). {@code WeaponGroupType} has exactly two constants, LINKED and ALTERNATING, so
     * the mapping is total; the replicator does the conversion at the edge.
     */
    public record WeaponGroup(List<String> slots, boolean alternating, boolean autofire) {

        /** Number of {@code |}-separated fields in one encoded group. */
        public static final int FIELD_COUNT = 3;

        public WeaponGroup {
            slots = copyList(slots);
        }

        /** A group is its own little {@link CoopDelimited} line, carried in one level-3 cell. */
        public String encode() {
            return CoopDelimited.field(joinList(slots))
                    + '|' + (alternating ? '1' : '0')
                    + '|' + (autofire ? '1' : '0');
        }

        public static WeaponGroup decode(String encoded) {
            Objects.requireNonNull(encoded, "encoded");
            List<String> f = CoopDelimited.split(encoded);
            if (f.size() != FIELD_COUNT) {
                throw new IllegalArgumentException("Expected " + FIELD_COUNT
                        + " weapon group fields, got " + f.size() + " in: " + encoded);
            }
            return new WeaponGroup(splitList(f.get(0)),
                    "1".equals(f.get(1).trim()),
                    "1".equals(f.get(2).trim()));
        }
    }

    // ---- Level-3 encoding ----------------------------------------------------------------------

    static String joinList(List<String> values) {
        StringBuilder out = new StringBuilder();
        for (String value : values) {
            if (out.length() > 0) {
                out.append(',');
            }
            out.append(cell(value));
        }
        return out.toString();
    }

    static List<String> splitList(String encoded) {
        List<String> out = new ArrayList<>();
        if (encoded == null || encoded.isEmpty()) {
            return out;
        }
        for (String raw : splitCells(encoded)) {
            if (!raw.isEmpty()) {
                out.add(uncell(raw));
            }
        }
        return out;
    }

    static String joinMap(Map<String, String> values) {
        StringBuilder out = new StringBuilder();
        for (Map.Entry<String, String> entry : values.entrySet()) {
            if (out.length() > 0) {
                out.append(',');
            }
            out.append(cell(entry.getKey())).append('=').append(cell(entry.getValue()));
        }
        return out.toString();
    }

    static Map<String, String> splitMap(String encoded) {
        Map<String, String> out = new LinkedHashMap<>();
        if (encoded == null || encoded.isEmpty()) {
            return out;
        }
        for (String pair : splitCells(encoded)) {
            if (pair.isEmpty()) {
                continue;
            }
            int split = indexOfUnescaped(pair, '=');
            if (split < 0) {
                throw new IllegalArgumentException("Malformed key=value cell: " + pair);
            }
            out.put(uncell(pair.substring(0, split)), uncell(pair.substring(split + 1)));
        }
        return out;
    }

    /** Each group's own encoded line, cell-escaped into the level-3 comma list. */
    static String joinGroups(List<WeaponGroup> groups) {
        List<String> lines = new ArrayList<>(groups.size());
        for (WeaponGroup group : groups) {
            lines.add(group.encode());
        }
        return joinList(lines);
    }

    static List<WeaponGroup> splitGroups(String encoded) {
        List<WeaponGroup> out = new ArrayList<>();
        for (String line : splitList(encoded)) {
            out.add(WeaponGroup.decode(line));
        }
        return out;
    }

    /** {@code slotId=<whole encoded module detail>}, one cell per module slot. */
    static String joinModules(Map<String, CoopShipDetail> values) {
        StringBuilder out = new StringBuilder();
        for (Map.Entry<String, CoopShipDetail> entry : values.entrySet()) {
            if (out.length() > 0) {
                out.append(',');
            }
            out.append(cell(entry.getKey())).append('=').append(cell(entry.getValue().encode()));
        }
        return out.toString();
    }

    private static Map<String, CoopShipDetail> splitModules(String encoded, int depth) {
        Map<String, CoopShipDetail> out = new LinkedHashMap<>();
        if (encoded == null || encoded.isEmpty()) {
            return out;
        }
        for (String pair : splitCells(encoded)) {
            if (pair.isEmpty()) {
                continue;
            }
            int split = indexOfUnescaped(pair, '=');
            if (split < 0) {
                throw new IllegalArgumentException("Malformed module slot=detail cell: " + pair);
            }
            out.put(uncell(pair.substring(0, split)),
                    decode(uncell(pair.substring(split + 1)), depth + 1));
        }
        return out;
    }

    /** Escapes one level-3 element so {@code ,} and {@code =} stay structural. */
    private static String cell(String value) {
        String text = value == null ? "" : value;
        StringBuilder out = new StringBuilder(text.length());
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            switch (c) {
                case '\\' -> out.append("\\\\");
                case ',' -> out.append("\\c");
                case '=' -> out.append("\\e");
                default -> out.append(c);
            }
        }
        return out.toString();
    }

    private static String uncell(String value) {
        StringBuilder out = new StringBuilder(value.length());
        boolean escaped = false;
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if (escaped) {
                switch (c) {
                    case '\\' -> out.append('\\');
                    case 'c' -> out.append(',');
                    case 'e' -> out.append('=');
                    default -> out.append(c);
                }
                escaped = false;
            } else if (c == '\\') {
                escaped = true;
            } else {
                out.append(c);
            }
        }
        return out.toString();
    }

    /** Splits on {@code ,} that are not part of an escape sequence; cells stay escaped. */
    private static List<String> splitCells(String encoded) {
        List<String> cells = new ArrayList<>();
        StringBuilder token = new StringBuilder();
        boolean escaped = false;
        for (int i = 0; i < encoded.length(); i++) {
            char c = encoded.charAt(i);
            if (escaped) {
                token.append(c);
                escaped = false;
            } else if (c == '\\') {
                token.append(c);
                escaped = true;
            } else if (c == ',') {
                cells.add(token.toString());
                token.setLength(0);
            } else {
                token.append(c);
            }
        }
        cells.add(token.toString());
        // Cells come back still escaped: list values are unescaped by the caller, and map cells have
        // to be split on their unescaped '=' before either half can be unescaped.
        return cells;
    }

    private static int indexOfUnescaped(String text, char target) {
        boolean escaped = false;
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            if (escaped) {
                escaped = false;
            } else if (c == '\\') {
                escaped = true;
            } else if (c == target) {
                return i;
            }
        }
        return -1;
    }

    private static List<String> copyList(List<String> values) {
        List<String> copy = new ArrayList<>();
        if (values != null) {
            for (String value : values) {
                if (value != null && !value.isBlank()) {
                    copy.add(value);
                }
            }
        }
        return List.copyOf(copy);
    }

    private static Map<String, String> copyMap(Map<String, String> values) {
        Map<String, String> copy = new LinkedHashMap<>();
        if (values != null) {
            for (Map.Entry<String, String> entry : values.entrySet()) {
                if (entry.getKey() == null || entry.getKey().isBlank()
                        || entry.getValue() == null || entry.getValue().isBlank()) {
                    continue;
                }
                copy.put(entry.getKey(), entry.getValue());
            }
        }
        return Collections.unmodifiableMap(copy);
    }

    private static List<WeaponGroup> copyGroups(List<WeaponGroup> groups) {
        List<WeaponGroup> copy = new ArrayList<>();
        if (groups != null) {
            for (WeaponGroup group : groups) {
                if (group != null) {
                    copy.add(group);
                }
            }
        }
        return List.copyOf(copy);
    }

    private static Map<String, CoopShipDetail> copyModules(Map<String, CoopShipDetail> values) {
        Map<String, CoopShipDetail> copy = new LinkedHashMap<>();
        if (values != null) {
            for (Map.Entry<String, CoopShipDetail> entry : values.entrySet()) {
                if (entry.getKey() == null || entry.getKey().isBlank() || entry.getValue() == null) {
                    continue;
                }
                copy.put(entry.getKey(), entry.getValue());
            }
        }
        return Collections.unmodifiableMap(copy);
    }

    /**
     * Hull fraction is a 0..1 quantity everywhere in the engine ({@code FleetMemberStatusAPI}
     * javadoc: "From 0 to 1"), and {@code setHullFraction} is not documented to clamp. A blob that
     * claimed 1.4 would hand the receiving engine an out-of-range hull, so the record is the fence.
     */
    private static float clampFraction(float value) {
        if (Float.isNaN(value)) {
            return 1f;
        }
        return Math.max(0f, Math.min(1f, value));
    }

    /** A field written by an older or hand-built blob may be empty; that reads as "undamaged". */
    private static float parseFraction(String text) {
        String trimmed = text == null ? "" : text.trim();
        return trimmed.isEmpty() ? 1f : Float.parseFloat(trimmed);
    }

    /** Locale-independent, so a comma-decimal locale cannot corrupt the wire format. */
    private static String floatText(float value) {
        return String.format(Locale.ROOT, "%.4f", value);
    }

}
